### ISSUE TITLE
How Can I set unsubscribe link while sending email via API

### ISSUE THREAD

**Issue by VirendraArekar** [sendgrid/smtpapi-php#100]
How add it unsubscribe  url in email body
`$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://api.sendgrid.com/v3/campaigns",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "{\"title\":\"March Newsletter\",\"subject\":\"New Products for Spring!\",\"sender_id\":875149,\"list_ids\":[4375245],\"segment_ids\":[123124],\"categories\":[\"spring line\"],\"custom_unsubscribe_url\":\"http:://TestUrl/unsubscribe\",\"html_content\":\"<html><head><title></title></head><body><p>Check out follow this link to be removed<unsubscribe>unsubscribe instantly</unsubscribe></p></body></html>\",\"plain_content\":\"Check out our spring line!\"}",
  CURLOPT_HTTPHEADER => array(
    "authorization: Bearer MySendGridKey",
    "content-type: application/json"
  ),
));`

Please help me

**Comment by thinkingserious** [comment]
Hello @VirendraArekar,

I have added this to my backlog for further review. In the mean-time, you might find this easier using our official [PHP SDK](https://github.com/sendgrid/sendgrid-php).

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @VirendraArekar,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
