### ISSUE TITLE
Bug fix for addTo() recipients with commas in their name

### ISSUE THREAD

**Issue by eddiezane** [sendgrid/smtpapi-php#7]
> sendgrid/vendor/sendgrid/smtpapi/lib/Smtpapi/Header.php
> 
> If there is a comma in the value of $name, addTo() will not escape or quote it, leading to a faulty To: header.
> 
> I recommend changing line 16 to:
> 
> $this->to[] = ($name ? '"' . preg_replace('{"}', '&quot;', $name) . '" ' : $email);

Moved from https://github.com/sendgrid/sendgrid-php/issues/101.

Need to investigate if still an issue.

**Comment by marshallsherman** [comment]
Hey! This seems pretty straightforward. Is the goal to implement the recommended change or come up with something else?

**Comment by Braunson** [comment]
I think there's a few options here:

1. Escape them 
2. Quote them
3. `urlencode` it
4. [Change the encoding](https://stackoverflow.com/a/12036263/610880)

Before doing the above, we can detect them using something like:

```php
if (!is_null($name) && preg_match('/[^a-zA-Z._]+/', $name, $matches)) {
    // Do whatever here to $name
}
```

That being said, shouldn't the user be filtering the incoming data? Does SwiftMailer do anything to mitigate against this?

**Comment by WilliamMollenkopfIII** [comment]
@Braunson 
It looks like you should be able to have a name of "Bob's Burgers" for example which would allow for ' to be a part of the name for the e-mail right?

That part I'm not too sure on. Also, I'm not sure if urlencode would actually be supported by all mail clients - some might just display the %20 (space) ?.

The same might be true for even escaped characters.
(Might display as "Bob\'s Burgers" instead of "Bob's Burgers")

Maybe the string concatenation that uses the name variable has the problem somehow?
Example: 
`$name = "Bob's Burgers";
$test = 'Name is $name'`

If $test is assigned as:
`$test = "Name is " . $test;`

I don't suspect there would be any issues with using the $name variable with a single quote or any other special character then, right? 

Honestly, I'm not too sure and could be wrong about my assumptions.
I just wanted to throw that thought out there to see if it would help at least.

**Comment by jmauerhan** [comment]
Is the problem a comma, or a single quote / apostrophe? 

I tried this example, just copied a bit from the tests and added a string with a comma:
```
$header = new Smtpapi\Header();
$header->addTo('foo@example.com', 'Mike, John and Jane Bar');
var_dump($header->jsonString());
```

And the result dumped is this json: 
`{"to":["Mike, John and Jane Bar <foo@example.com>"]}"`

It sounds like quoting the name is an easy fix, so then the desired result would be: 
`{"to":["\"Mike, John and Jane Bar\" <foo@example.com>"]}"`

Is this correct?
